### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by camilledesvigne** [boisgera/python-advanced-eval#3]
AttributeError: 'PyPercentSerializer' object has no attribute 'to_py_percent'

**Comment by boisgera** [comment]
A priori dans l'énoncé on vous demande

> **Question 13: Sauvegarde (py-percent)**
>
> Nous pouvons aussi utiliser ce format Notebook "objet" pour réaliser des transformations de format, par exemple le transformer au format "py-percent":
>
>    - 🚀  **Développez les méthodes de la classe PyPercentSerializer.**
>

[Le squelette de la classe `PyPercentSerializer`](https://github.com/boisgera/python-advanced-eval/blob/master/notebook_v1.py#L130) comporte bien [une méthode `to_py_percent`](https://github.com/boisgera/python-advanced-eval/blob/bafbd225ac1ccb0da45fe6abe47345a7efd4512d/notebook_v1.py#L154) (non implémentée) qu'appelle [le test associé](https://github.com/boisgera/python-advanced-eval/blob/bafbd225ac1ccb0da45fe6abe47345a7efd4512d/notebook_v1.py#L139) (c'est le seul endroit du fichier v1 ou cette méthode est testée a priori).

Je ne suis donc pas sûr de comprendre comment on pourrait obtenir l'erreur

> `AttributeError: 'PyPercentSerializer' object has no attribute 'to_py_percent'`

en faisant tourner les tests, à moins d'effacer le squelette de la méthode `to_py_percent` de la classe `PyPercentSerializer` ?

**Comment by camilledesvigne** [comment]
Bonsoir Monsieur,

En effet, il s’agit d’une erreur de ma part, j’avais renommé par erreur ma fonction to_py_percent en serialize_percent. Désolée …
Bonne fin de semaine,

Camille



jeudi 6 janvier 2022 à 17:11 +0100 de ***@***.***  ***@***.***>:
